$kind: http-request
name: product:createNewProduct
url: localhost:3003/admin/product/create
method: POST
body:
  type: formdata
  content:
    - type: text
      key: productCollection
      value: DISH
      description: ""
      disabled: false
    - type: text
      key: productName
      value: Qovurma
      description: ""
      disabled: false
    - type: text
      key: productPrice
      value: "15"
      description: ""
      disabled: false
    - type: text
      key: productLeftCount
      value: "100"
      description: ""
      disabled: false
    - type: text
      key: productSize
      value: LARGE
      description: ""
      disabled: false
    - type: text
      key: productVolume
      value: "1"
      description: ""
      disabled: true
    - type: text
      key: productDecs
      value: Delicious meal
      description: ""
      disabled: false
    - type: file
      key: productImages
      src:
        - /Users/a1234/Downloads/_ (2).jpeg
        - /Users/a1234/Downloads/_ (3).jpeg
        - /Users/a1234/Downloads/Côte de bœuf grillée 🥩🔥.jpeg
      description: ""
      disabled: false
order: 4431704487369516
