$kind: http-request
name: product:getProducts
url: localhost:3003/product/all?order=createdAt&page=1&limit=3&productCollection=DISH&search=Steak
method: GET
queryParams:
  order: createdAt
  page: "1"
  limit: "3"
  productCollection: DISH
  search: Steak
body:
  type: json
  content: ""
order: 4375530412747422
